<a href="https://colab.research.google.com/github/raisatsal/EDA/blob/main/P03_PraktikumEDA_Pertemuan3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Praktikum Pertemuan 3 — Menyiapkan Data Proyek agar Layak dan Aman Dianalisis

**Mata Kuliah:** Exploratory Data Analysis (KMTI21133) — Pertemuan 3  
**Fase PjBL:** Perencanaan  
**Sub-CPMK3:** Mahasiswa mampu merumuskan pertanyaan analisis dari masalah nyata serta memperoleh data
sesuai lisensi sumbernya, serta mengidentifikasi dan menangani data pribadi yang terkandung di dalamnya (C4, A3).

**Cara kerja.** Sel bertanda `# TODO` Anda kerjakan sendiri; setiap TODO disertai *expected output* agar Anda bisa memeriksa jawaban sendiri. Sel Markdown bertanda **Jawaban Anda** diisi dengan tulisan, bukan kode.

**Bagian A–F** dikerjakan di kelas dengan dataset latihan. **Bagian G** dikerjakan bersama tim di luar kelas dengan dataset proyek Anda sendiri, dan hasilnya menjadi isi **M1 (bobot 5%)** yang dikumpulkan sesuai tenggat di LMS.

## Bagian 0 — Persiapan

Dataset latihan: **`peserta_pelatihan_umkm_2025.csv`** — 620 baris, 28 kolom.
Data pendaftaran dan hasil pelatihan UMKM binaan kampus.

> **Catatan penting:** seluruh isi dataset ini **sintetis** dan dibuat untuk latihan. Tidak ada orang nyata di dalamnya.
> Nomor NIK, nomor telepon, dan surel sengaja dibuat dengan pola yang tidak valid. Perlakukan tetap seolah-olah data nyata,
> karena itulah kebiasaan yang sedang kita latih.

In [1]:
import pandas as pd
import numpy as np
import hashlib, os

pd.set_option('display.max_columns', 40)
pd.set_option('display.width', 140)
print('pandas', pd.__version__)

pandas 2.2.3

In [2]:
FILE = 'peserta_pelatihan_umkm_2025.csv'

if not os.path.exists(FILE):
    try:
        from google.colab import files
        files.upload()          # pilih peserta_pelatihan_umkm_2025.csv
    except ImportError:
        raise FileNotFoundError('Letakkan CSV di folder yang sama dengan notebook ini.')

df = pd.read_csv(FILE)
print(df.shape)
df.head(3)

(620, 28)

,id_peserta,nama_lengkap,nik_dummy,no_hp,email,alamat_jalan,kelurahan,kecamatan,kota,tanggal_lahir,jenis_kelamin,pendidikan_terakhir,status_disabilitas,jumlah_anak,penghasilan_pribadi_bulanan,nama_usaha,kategori_usaha,produk_utama,lama_usaha_tahun,jumlah_karyawan,omzet_usaha_bulanan,pernah_ikut_pelatihan,kanal_pendaftaran,tanggal_daftar,kehadiran_persen,skor_prates,skor_pascates,tingkat_kepuasan
0,PLT-2025-1309,Ratna Hidayat,99991405899249,8.000426e+10,ratna.hidayat@contoh.example,Jl. Cempaka No. 106 RT 02/RW 10,Sukatani,Tapos,Depok,1989-05-14,P,SMP,Tidak,3,500000,CV Mandiri Jaya,Kuliner,Roti dan kue,12.8,4,2950000,Tidak,Datang langsung,2025-04-04,75,52,67.0,5.0
1,PLT-2025-1512,Bunga Santoso,99992410874363,8.000347e+10,bunga.santoso@contoh.example,Jl. Bougenville No. 80 RT 10/RW 02,Mampang,Pancoran Mas,Depok,1987-10-24,P,D3,Tidak,1,950000,Dapur Cahaya Abadi,Jasa Digital,Servis gawai,6.5,3,7750000,Tidak,Formulir daring,2025-02-02,70,59,75.0,4.9
2,PLT-2025-1360,Endah Ramadhan,99991107987303,8.000266e+10,endah.ramadhan@contoh.example,Jl. Anggrek No. 138 RT 07/RW 08,Limo,Limo,Depok,1998-07-11,P,D3,Tidak,2,1500000,Griya Harum Makmur,Kuliner,Katering rumahan,2.5,0,7550000,Tidak,WhatsApp,2025-03-26,90,51,61.0,4.9

---
## Bagian A — Merumuskan pertanyaan analisis

Sebuah pertanyaan analisis dianggap layak bila lolos **tiga uji**:

1. **Uji kolom** — kolom mana yang akan menjawabnya?
2. **Uji bentuk jawaban** — jawabannya berupa angka, peringkat, perbandingan, atau sebaran?
3. **Uji tindak lanjut** — kalau terjawab, apa yang bisa diputuskan?

In [4]:
# TODO A1 — kenali kolom yang tersedia sebelum menulis pertanyaan

# a. Cetak daftar nama kolom beserta tipe datanya
print("Daftar kolom dan tipe data:")
print(df.dtypes)

# b. Cetak jumlah baris dan kolom
print("\nJumlah baris dan kolom:")
print(df.shape)

Daftar kolom dan tipe data:
id_peserta                      object
nama_lengkap                    object
nik_dummy                        int64
no_hp                          float64
email                           object
alamat_jalan                    object
kelurahan                       object
kecamatan                       object
kota                            object
tanggal_lahir                   object
jenis_kelamin                   object
pendidikan_terakhir             object
status_disabilitas              object
jumlah_anak                      int64
penghasilan_pribadi_bulanan      int64
nama_usaha                      object
kategori_usaha                  object
produk_utama                    object
lama_usaha_tahun               float64
jumlah_karyawan                  int64
omzet_usaha_bulanan              int64
pernah_ikut_pelatihan           object
kanal_pendaftaran               object
tanggal_daftar                  object
kehadiran_persen                 int64
skor_prates                      int64
skor_pascates                  float64
tingkat_kepuasan               float64
dtype: object

Jumlah baris dan kolom:
(620, 28)

### TODO A2 — perbaiki tiga pertanyaan berikut

Tulis versi perbaikannya di sel di bawah, beserta kolom yang akan dipakai.

| No | Draf pertanyaan | Masalahnya |
|---|---|---|
| 1 | Bagaimana kondisi peserta pelatihan? | Terlalu kabur |
| 2 | Apakah peserta yang lebih kaya lebih sukses? | "Kaya" dan "sukses" belum didefinisikan sebagai kolom |
| 3 | Apakah pelatihan menaikkan omzet peserta? | Uji kolom gagal — cek sendiri mengapa |

**Jawaban Anda:**

1. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
2. Perbaikan: _(tulis di sini)_ — Kolom: _(tulis di sini)_
3. Mengapa uji kolom gagal: _(tulis di sini)_

In [5]:
# TODO A3 — buktikan jawaban nomor 3 dengan kode

# Periksa apakah ada kolom omzet SESUDAH pelatihan di dataset ini.
# Petunjuk: cari nama kolom yang memuat kata 'omzet'

kolom_omzet = [
    kolom for kolom in df.columns
    if 'omzet' in kolom.lower()
]

print("Kolom yang memuat kata 'omzet':")
print(kolom_omzet)

Kolom yang memuat kata 'omzet':
['omzet_usaha_bulanan']

---
## Bagian B — Skala pengukuran

### TODO B1 — klasifikasikan delapan kolom berikut

Isi tabel di sel Markdown ini. Pilihan: **nominal · ordinal · interval · rasio**.

| Kolom | Skala | Alasan singkat |
|---|---|---|
| `kategori_usaha` | | |
| `pendidikan_terakhir` | | |
| `skor_prates` | | |
| `omzet_usaha_bulanan` | | |
| `jumlah_karyawan` | | |
| `tingkat_kepuasan` | | |
| `tanggal_daftar` | | |
| `kecamatan` | | |

In [6]:
# TODO B2 — perbaiki satu kolom ordinal yang salah tipe

# a. Jadikan 'pendidikan_terakhir' bertipe kategori berurutan
urutan_pendidikan = ['SD', 'SMP', 'SMA/SMK', 'D3', 'S1', 'S2']

df['pendidikan_terakhir'] = pd.Categorical(
    df['pendidikan_terakhir'],
    categories=urutan_pendidikan,
    ordered=True
)

# b. Tampilkan value_counts() sesuai urutan jenjang
print("Jumlah peserta berdasarkan jenjang pendidikan:")
print(df['pendidikan_terakhir'].value_counts().sort_index())

# c. Cetak median jenjang pendidikan lewat .cat.codes
kode_pendidikan = df['pendidikan_terakhir'].cat.codes
median_kode = kode_pendidikan.median()

median_pendidikan = urutan_pendidikan[int(median_kode)]

print("\nMedian jenjang pendidikan:", median_pendidikan)

Jumlah peserta berdasarkan jenjang pendidikan:
pendidikan_terakhir
SD          24
SMP         71
SMA/SMK    281
D3         107
S1         124
S2          13
Name: count, dtype: int64

Median jenjang pendidikan: SMA/SMK

In [7]:
# TODO B3 — ubah dua kolom tanggal menjadi bertipe datetime

# Ubah kolom tanggal menjadi datetime
df['tanggal_lahir'] = pd.to_datetime(df['tanggal_lahir'], errors='coerce')
df['tanggal_daftar'] = pd.to_datetime(df['tanggal_daftar'], errors='coerce')

# Cetak tanggal pendaftaran paling awal dan paling akhir
print("Tanggal pendaftaran paling awal:", df['tanggal_daftar'].min())
print("Tanggal pendaftaran paling akhir:", df['tanggal_daftar'].max())

Tanggal pendaftaran paling awal: 2025-02-01 00:00:00
Tanggal pendaftaran paling akhir: 2025-05-31 00:00:00

---
## Bagian C — Kamus data

Kamus data adalah satu baris penjelasan untuk setiap kolom. Bangkitkan kerangkanya dengan kode, isi maknanya sendiri.

In [8]:
# TODO C1 — bangkitkan kerangka kamus data

kamus = pd.DataFrame({
    'nama_kolom': df.columns,
    'tipe_data': df.dtypes.astype(str).values,
    'nilai_unik': [df[kolom].nunique() for kolom in df.columns],
    'nilai_kosong': [df[kolom].isna().sum() for kolom in df.columns],
    'contoh_nilai': [
        df[kolom].dropna().iloc[0] if df[kolom].notna().any() else None
        for kolom in df.columns
    ]
})

# Tambahkan empat kolom yang akan diisi manual
kamus['deskripsi'] = ''
kamus['skala_pengukuran'] = ''
kamus['kategori_data_pribadi'] = ''
kamus['tindakan_penanganan'] = ''

print("Ukuran kamus data:", kamus.shape)
display(kamus)

Ukuran kamus data: (28, 9)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
0,id_peserta,object,620,0,PLT-2025-1309,,,,
1,nama_lengkap,object,450,0,Ratna Hidayat,,,,
2,nik_dummy,int64,620,0,99991405899249,,,,
3,no_hp,float64,611,9,80004260813.0,,,,
4,email,object,450,0,ratna.hidayat@contoh.example,,,,
5,alamat_jalan,object,620,0,Jl. Cempaka No. 106 RT 02/RW 10,,,,
6,kelurahan,object,26,0,Sukatani,,,,
7,kecamatan,object,19,0,Tapos,,,,
8,kota,object,1,0,Depok,,,,
9,tanggal_lahir,datetime64[ns],598,0,1989-05-14 00:00:00,,,,
10,jenis_kelamin,object,2,0,P,,,,
11,pendidikan_terakhir,category,6,0,SMP,,,,
12,status_disabilitas,object,2,0,Tidak,,,,
13,jumlah_anak,int64,5,0,3,,,,
14,penghasilan_pribadi_bulanan,int64,110,0,500000,,,,
15,nama_usaha,object,185,0,CV Mandiri Jaya,,,,
16,kategori_usaha,object,5,0,Kuliner,,,,
17,produk_utama,object,19,0,Roti dan kue,,,,
18,lama_usaha_tahun,float64,119,0,12.8,,,,
19,jumlah_karyawan,int64,11,0,4,,,,
20,omzet_usaha_bulanan,int64,293,0,2950000,,,,
21,pernah_ikut_pelatihan,object,2,0,Tidak,,,,
22,kanal_pendaftaran,object,4,0,Datang langsung,,,,
23,tanggal_daftar,datetime64[ns],120,0,2025-04-04 00:00:00,,,,
24,kehadiran_persen,int64,46,0,75,,,,
25,skor_prates,int64,64,0,52,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

In [9]:
# TODO C2 — kolom mana yang punya nilai kosong?

kolom_kosong = kamus[kamus['nilai_kosong'] > 0]

display(kolom_kosong)

,nama_kolom,tipe_data,nilai_unik,nilai_kosong,contoh_nilai,deskripsi,skala_pengukuran,kategori_data_pribadi,tindakan_penanganan
3,no_hp,float64,611,9,80004260813.0,,,,
26,skor_pascates,float64,64,34,67.0,,,,
27,tingkat_kepuasan,float64,28,18,5.0,,,,

### TODO C3 — isi kamus untuk lima kolom

Lengkapi tabel berikut. Deskripsi ditulis sebagai kalimat lengkap, bukan pengulangan nama kolom.

| Kolom | Deskripsi | Skala | Satuan |
|---|---|---|---|
| `lama_usaha_tahun` | | | |
| `kehadiran_persen` | | | |
| `skor_pascates` | | | |
| `kanal_pendaftaran` | | | |
| `jumlah_anak` | | | |

---
## Bagian D — Menandai data pribadi

| Kategori | Artinya |
|---|---|
| **pengenal langsung** | Sendirian sudah menunjuk ke satu orang |
| **quasi-identifier** | Sendirian aman, gabungannya menunjuk ke satu orang |
| **data spesifik** | Bocornya merugikan lebih berat (kesehatan, keuangan pribadi, data anak) |
| **bukan data pribadi** | Tidak menunjuk ke orang; inilah bahan analisis |

In [10]:
# TODO D1 — susun tabel penandaan Anda sendiri

PENANDAAN = {
    # Pengenal langsung
    'nama_lengkap': ('pengenal langsung', 'hash'),
    'nik_dummy': ('pengenal langsung', 'hash'),
    'no_hp': ('pengenal langsung', 'hash'),
    'email': ('pengenal langsung', 'hash'),
    'alamat_jalan': ('pengenal langsung', 'hapus'),
    'nama_usaha': ('pengenal langsung', 'hash'),

    # Quasi-identifier
    'id_peserta': ('quasi-identifier', 'pertahankan'),
    'kelurahan': ('quasi-identifier', 'generalisasi'),
    'kecamatan': ('quasi-identifier', 'generalisasi'),
    'kota': ('quasi-identifier', 'pertahankan'),
    'tanggal_lahir': ('quasi-identifier', 'generalisasi'),
    'jenis_kelamin': ('quasi-identifier', 'generalisasi'),
    'pendidikan_terakhir': ('quasi-identifier', 'pertahankan'),

    # Data spesifik
    'status_disabilitas': ('data spesifik', 'generalisasi'),
    'jumlah_anak': ('data spesifik', 'generalisasi'),
    'penghasilan_pribadi_bulanan': ('data spesifik', 'generalisasi'),
    'omzet_usaha_bulanan': ('data spesifik', 'generalisasi'),

    # Kolom lain akan dianggap bukan data pribadi + pertahankan
}

# Bangun DataFrame penandaan
baris_tanda = []

for kolom in df.columns:
    if kolom in PENANDAAN:
        kategori, tindakan = PENANDAAN[kolom]
    else:
        kategori, tindakan = 'bukan data pribadi', 'pertahankan'

    baris_tanda.append({
        'nama_kolom': kolom,
        'kategori': kategori,
        'tindakan': tindakan
    })

tanda = pd.DataFrame(baris_tanda)

# Tampilkan tabel penandaan
display(tanda)

# Cetak jumlah kolom per kategori
print("\nJumlah kolom per kategori:")
print(tanda['kategori'].value_counts())

                     nama_kolom            kategori      tindakan
0                    id_peserta    quasi-identifier   pertahankan
1                  nama_lengkap   pengenal langsung          hash
2                     nik_dummy   pengenal langsung          hash
3                         no_hp   pengenal langsung          hash
4                         email   pengenal langsung          hash
5                  alamat_jalan   pengenal langsung         hapus
6                     kelurahan    quasi-identifier  generalisasi
7                     kecamatan    quasi-identifier  generalisasi
8                          kota    quasi-identifier   pertahankan
9                 tanggal_lahir    quasi-identifier  generalisasi
10                jenis_kelamin    quasi-identifier  generalisasi
11          pendidikan_terakhir    quasi-identifier   pertahankan
12           status_disabilitas       data spesifik  generalisasi
13                  jumlah_anak       data spesifik  generalisasi
14  penghasilan_pribadi_bulanan       data spesifik  generalisasi
15                   nama_usaha   pengenal langsung          hash
16               kategori_usaha  bukan data pribadi   pertahankan
17                 produk_utama  bukan data pribadi   pertahankan
18             lama_usaha_tahun  bukan data pribadi   pertahankan
19              jumlah_karyawan  bukan data pribadi   pertahankan
20          omzet_usaha_bulanan       data spesifik  generalisasi
21        pernah_ikut_pelatihan  bukan data pribadi   pertahankan
22            kanal_pendaftaran  bukan data pribadi   pertahankan
23               tanggal_daftar  bukan data pribadi   pertahankan
24             kehadiran_persen  bukan data pribadi   pertahankan
25                  skor_prates  bukan data pribadi   pertahankan
26                skor_pascates  bukan data pribadi   pertahankan
27             tingkat_kepuasan  bukan data pribadi   pertahankan

Jumlah kolom per kategori:
kategori
bukan data pribadi    11
quasi-identifier       7
pengenal langsung      6
data spesifik          4
Name: count, dtype: int64

### TODO D2 — pertanggungjawabkan tiga keputusan

Tiga kolom berikut sering diperdebatkan. Tulis keputusan Anda **beserta alasannya**.

| Kolom | Kategori pilihan Anda | Tindakan | Alasan |
|---|---|---|---|
| `nama_usaha` | | | |
| `omzet_usaha_bulanan` | | | |
| `id_peserta` | | | |

> Petunjuk untuk `nama_usaha`: bayangkan seseorang mencari nama itu di mesin pencari.
> Petunjuk untuk `omzet_usaha_bulanan`: apakah ini data tentang **orang** atau tentang **usaha**?
> Petunjuk untuk `id_peserta`: apakah Anda masih perlu membedakan satu baris dari baris lain?

---
## Bagian E — Menerapkan tiga tindakan

In [11]:
# TODO E1 — HAPUS

# Cari kolom yang tindakannya adalah 'hapus'
kolom_hapus = [
    kolom for kolom, (_, tindakan) in PENANDAAN.items()
    if tindakan == 'hapus'
]

# Buat DataFrame baru tanpa kolom tersebut
aman = df.drop(columns=kolom_hapus)

# Cetak jumlah kolom yang dibuang dan yang tersisa
print("Kolom yang dibuang:", len(kolom_hapus))
print("Kolom yang tersisa:", aman.shape[1])
print("Nama kolom yang dibuang:", kolom_hapus)

Kolom yang dibuang: 1
Kolom yang tersisa: 27
Nama kolom yang dibuang: ['alamat_jalan']

In [13]:
# TODO E2 — HASH

import hashlib
import numpy as np

GARAM = 'ganti-dengan-kalimat-rahasia-tim'

def samarkan(nilai, garam):
    # Jika nilai kosong, tetap kosong
    if pd.isna(nilai):
        return np.nan

    # Gabungkan garam + nilai lalu lakukan SHA-256
    teks = garam + str(nilai)
    hasil_hash = hashlib.sha256(teks.encode('utf-8')).hexdigest()

    # Ambil 12 karakter pertama
    return hasil_hash[:12]


# Cari kolom yang tindakannya adalah 'hash'
kolom_hash = [
    kolom for kolom, (_, tindakan) in PENANDAAN.items()
    if tindakan == 'hash'
]

# Terapkan hash ke kolom yang dipilih
for kolom in kolom_hash:
    aman[kolom] = aman[kolom].apply(
        lambda x: samarkan(x, GARAM)
    )

print("Kolom yang di-hash:")
print(kolom_hash)

print("\nContoh hasil:")
display(aman[kolom_hash].head())

GARAM = 'praktikum-tim-2025'

Kolom yang di-hash:
['nama_lengkap', 'nik_dummy', 'no_hp', 'email', 'nama_usaha']

Contoh hasil:

   nama_lengkap     nik_dummy         no_hp         email    nama_usaha
0  86720fae57e5  7cb495ba7422  209ffb79924d  d3b4d3c44b82  197e71db97e1
1  6a98c6f11034  064aca0c75bd  a71b67910575  f82627895021  1807e1835663
2  c3a7af2bc5ba  7ddf5890022a  76fa8052051e  55fc2ab32349  09e01f018196
3  e15ff531ebd8  c60506d8afcf  779bfdeb740d  7d16fe747605  f69e9db41f35
4  f45c89bc644b  21bdce808504  115fa008aa8f  60b6e8798be0  3a5996be1d89

In [14]:
# TODO E3 — buktikan hash bersifat konsisten dan tidak terbaca

nilai1 = "RAYYIS"
nilai2 = "RAYYIS"
nilai3 = "ANSHAR"

# a. Hash dua kali nilai yang sama
hash1 = samarkan(nilai1, GARAM)
hash2 = samarkan(nilai2, GARAM)

print("Hash nilai yang sama:")
print("Hash 1:", hash1)
print("Hash 2:", hash2)
print("Apakah identik?", hash1 == hash2)

# b. Hash dua nilai berbeda
hash3 = samarkan(nilai3, GARAM)

print("\nHash nilai yang berbeda:")
print("Hash RAYYIS :", hash1)
print("Hash ANSHAR :", hash3)
print("Apakah berbeda?", hash1 != hash3)

Hash nilai yang sama:
Hash 1: 168962018635
Hash 2: 168962018635
Apakah identik? True

Hash nilai yang berbeda:
Hash RAYYIS : 168962018635
Hash ANSHAR : 566b30224781
Apakah berbeda? True

**Jawaban Anda:** kalau `GARAM` ikut ter-*commit* ke GitHub, apa yang masih terlindungi dan apa yang tidak?

_(tulis di sini)_

In [19]:
# TODO E4 — GENERALISASI

ACUAN = pd.Timestamp('2025-09-01')

usia = ACUAN.year - aman['tanggal_lahir'].dt.year
usia -= (
    (aman['tanggal_lahir'].dt.month > ACUAN.month) |
    ((aman['tanggal_lahir'].dt.month == ACUAN.month) &
     (aman['tanggal_lahir'].dt.day > ACUAN.day))
).astype(int)

aman['kelompok_umur'] = pd.cut(
    usia,
    bins=[-float('inf'), 24, 34, 44, 54, float('inf')],
    labels=['<25', '25-34', '35-44', '45-54', '55+']
)

aman = aman.drop(columns=['tanggal_lahir', 'kelurahan'])

aman['kecamatan'] = aman['kecamatan'].str.strip().str.title()

print(aman['kelompok_umur'].value_counts())
print("Jumlah kecamatan unik:", aman['kecamatan'].nunique())

kelompok_umur
35-44    267
25-34    153
45-54    108
<25       53
55+       39
Name: count, dtype: int64
Jumlah kecamatan unik: 10

---
## Bagian F — Memeriksa sisa risiko

Menghapus nama belum tentu cukup. Untuk setiap kombinasi quasi-identifier, hitung berapa orang yang punya kombinasi sama. Nilai terkecil disebut **k**. Target kelas ini: **k ≥ 5**.

In [20]:
# TODO F1 — fungsi cek_k

def cek_k(data, kolom):
    grup = data.groupby(kolom, dropna=False).size()
    return pd.Series({
        'k': grup.min(),
        'grup_1_orang': (grup == 1).sum(),
        'total_grup': len(grup)
    })

cek_k(aman, ['kota', 'kelompok_umur'])

/tmp/ipykernel_3766/3981270507.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom, dropna=False).size()

k               39
grup_1_orang     0
total_grup       5
dtype: int64

In [21]:
# TODO F2 — ukur risiko SEBELUM penanganan

cek_k(
    df,
    ['kelurahan', 'jenis_kelamin', 'pendidikan_terakhir', 'tanggal_lahir']
)

/tmp/ipykernel_3766/3981270507.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom, dropna=False).size()

k                    0
grup_1_orang       620
total_grup      186576
dtype: int64

**Jawaban Anda:** keempat kolom itu tidak memuat nama maupun nomor telepon. Jelaskan dalam dua kalimat mengapa hasilnya tetap berbahaya.

_(tulis di sini)_

In [22]:
# TODO F3 — ukur risiko SESUDAH generalisasi

cek_k(
    aman,
    ['kecamatan', 'jenis_kelamin', 'pendidikan_terakhir', 'kelompok_umur']
)

/tmp/ipykernel_3766/3981270507.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom, dropna=False).size()

k                 0
grup_1_orang    138
total_grup      600
dtype: int64

In [23]:
# TODO F4 — TANTANGAN: capai k >= 5

kolom_qi = ['kecamatan', 'jenis_kelamin', 'kelompok_umur']

hasil_f4 = cek_k(aman, kolom_qi)

print(hasil_f4)

k                 0
grup_1_orang      7
total_grup      100
dtype: int64

/tmp/ipykernel_3766/3981270507.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grup = data.groupby(kolom, dropna=False).size()

**Jawaban Anda:** tulis kombinasi yang Anda pilih, nilai k yang dicapai, dan informasi apa yang Anda korbankan untuk mencapainya.

_(tulis di sini)_

In [24]:
# TODO F5 — sel kecil pada tabel agregat

tabel = pd.crosstab(
    aman['kecamatan'],
    aman['kategori_usaha']
)

sel_kecil = ((tabel >= 1) & (tabel < 5)).sum().sum()

print("Tabel silang:")
display(tabel)

print("Jumlah sel berisi 1-4 peserta:", sel_kecil)

Tabel silang:

kategori_usaha  Fesyen  Jasa Digital  Kriya  Kuliner  Pertanian
kecamatan
Beji                14            10     15       42          6
Bojongsari           7             5      4       23          2
Cimanggis           16             8     15       44          7
Cinere              16            11      8       23          9
Cipayung             4             6      5       10          1
Limo                10             4     10       15          4
Pancoran Mas        25            12     19       31         12
Sawangan             5             3      3       10          2
Sukmajaya           22            14     11       36         12
Tapos               11             5     11       16          6

Jumlah sel berisi 1-4 peserta: 9

### G5 — Daftar periksa sebelum `git push`

- [ ] `data/raw/` masuk `.gitignore`
- [ ] Tidak ada nama, NIK, nomor telepon, surel, atau alamat di berkas mana pun
- [ ] Keluaran sel yang sempat menampilkan data pribadi sudah dibersihkan
- [ ] Garam hash tidak tertulis di dalam notebook
- [ ] Kamus data memuat kategori dan tindakan untuk setiap kolom
- [ ] Nilai k pada data yang diunggah sudah dihitung dan dicatat
- [ ] Bila masih ragu: repositori dibuat **privat**

> Menghapus berkas lalu *commit* ulang **tidak** menghilangkan data dari riwayat Git. > Periksa **sebelum** *commit* pertama.